apiVersion: apps/v1
kind: Deployment
metadata:
  name: password-generator
spec:
  selector:
    matchLabels:
      app: password-generator
  replicas: 1
  template:
    metadata:
      labels:
        app: password-generator
    spec:
      containers:
        - name: password
          imagePullPolicy: Never
          image: password
          ports:
            - containerPort: 80
